### ISSUE TITLE
Chozen box near end of page.

### ISSUE THREAD

**Issue by Sovica** [losmicar/bselect#2]
If I embed the chozen box near the end of a page, it opens up all the select values downwards and the list goes beyond the viewable area of the browser window so entries get cut off. 
It would be a good idea to automatically re-position the select box to open upwards instead of downwards if it detects that it's near the end of a page and there is not enough room to show the entire select list.
This happens on Windows 10, latest Chrome version.

**Comment by losmicar** [comment]
Resolved with checkInView option.
