### ISSUE TITLE
Another issue when a form gets posted

### ISSUE THREAD

**Issue by MassaM-SDC** [losmicar/bselect#8]
When 2 or more of the **`bselect`** are in the form, only the data of the last one gets submitted to a **_PHP_**.

I tested with **`<form method="post" action="post.php">`** and in the PHP I have a **`var_dump($_POST)`** and it only received the last **`bselect-input`** selected **`index`** as shown below:

`array(1) {
  ["bselect-input"]=>
  string(1) "3"
}
`

**Comment by losmicar** [comment]
@MassaM-SDC Thanks for your feedback!

You should be able to set different input name attributes with **inputName** property.

```
$('#city').bselect({
		data : {1 : "Belgrade", 2 : "New York", 3 : "Viena", 4 : "Budapest"}, 
		inputName : "city",
		width : '200px',
		defaultText : "Select..."
	});
```
